services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: agencia-viagem-pgvector
    environment:
      POSTGRES_DB: agencia_viagem
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
